# Generated by Django 5.0.7 on 2024-07-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Literary Fiction', 'Literary Fiction'), ('Historical Fiction', 'Historical Fiction'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Biography', 'Biography'), ('Memoir', 'Memoir'), ('Self-Help', 'Self-Help'), ('History', 'History'), ('Travel', 'Travel'), ('True Crime', 'True Crime'), ('Science', 'Science'), ('Philosophy', 'Philosophy'), ('Picture Books', 'Picture Books'), ('Early Readers', 'Early Readers'), ('Middle Grade', 'Middle Grade'), ('Young Adult', 'Young Adult'), ('Textbooks', 'Textbooks'), ('Reference', 'Reference'), ('Essays', 'Essays'), ('Study Guides', 'Study Guides'), ('Classic Poetry', 'Classic Poetry'), ('Contemporary Poetry', 'Contemporary Poetry'), ('Anthologies', 'Anthologies'), ('Haiku', 'Haiku'), ('Plays', 'Plays'), ('Screenplays', 'Screenplays'), ('Manga', 'Manga'), ('Comics', 'Comics'), ('Graphic Non-Fiction', 'Graphic Non-Fiction'), ('Religious Texts', 'Religious Texts'), ('Spirituality', 'Spirituality'), ('Theology', 'Theology'), ('Nutrition', 'Nutrition'), ('Fitness', 'Fitness'), ('Mental Health', 'Mental Health'), ('Medical', 'Medical'), ('Management', 'Management'), ('Leadership', 'Leadership'), ('Finance', 'Finance'), ('Entrepreneurship', 'Entrepreneurship'), ('Programming', 'Programming'), ('Engineering', 'Engineering'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Cybersecurity', 'Cybersecurity'), ('Photography', 'Photography'), ('Painting', 'Painting'), ('Music Theory', 'Music Theory'), ('Art History', 'Art History'), ('Cooking', 'Cooking'), ('Gardening', 'Gardening'), ('Knitting', 'Knitting'), ('Woodworking', 'Woodworking'), ('Sports Biography', 'Sports Biography'), ('Training Guides', 'Training Guides'), ('Adventure', 'Adventure')], max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
